platform:
  - x64

branches:
  only:
    - master

environment:
  matrix:
    - PYVER: 36
    - PYVER: 35
    - PYVER: 27

install:
    # If there is a newer build queued for the same PR, cancel this one.
    - cmd: >
        .gen_ci_support\\ff_ci_pr_build.py -v
        --ci "appveyor"
        "%APPVEYOR_ACCOUNT_NAME%/%APPVEYOR_PROJECT_SLUG%"
        "%APPVEYOR_BUILD_NUMBER%"
        "%APPVEYOR_PULL_REQUEST_NUMBER%"

    # Install Miniconda.
    - cmd: call .appveyor_support\\install_miniconda.bat

    # Create the test environment.
    - cmd: set "CONDA_ENV_TYPE=tst_py%PYVER%"
    - cmd: call .appveyor_support\\create_env.bat

    # Install the package and dependencies.
    - cmd: pip install -e .

# Skip .NET project specific build phase.
build: off

# Run tests and measure test coverage.
test_script:
    - cmd: coverage erase
    - cmd: coverage run --source . setup.py test
    - cmd: coverage report -m

on_success:
    - cmd: set "CONDA_ENV_TYPE=dpl"
    - cmd: .appveyor_support\\create_env.bat
    - cmd: coveralls || exit 0
