sudo: false

language: generic

os: osx
osx_image: xcode9.4

branches:
  only:
    - master

env:
  - PYVER="37"
  - PYVER="36"
  - PYVER="35"
  - PYVER="27"

install:
  # Install and Configure Miniconda.
  - source .travis_support/install_miniconda.sh

  # Create the test environment.
  - export CONDA_ENV_TYPE="tst_py${PYVER}"
  - source .travis_support/create_env.sh

  # Install the package and dependencies.
  - pip install -e .

# Run tests and measure test coverage.
script:
  - coverage erase
  - coverage run --source . setup.py test
  - coverage report -m

# Report coverage.
after_success:
  - export CONDA_ENV_TYPE="dpl"
  - source .travis_support/create_env.sh
  - coveralls

# Disable email notifications.
notifications:
  email: false
