name: dask_image_doc_env

channels:
  - conda-forge

dependencies:
  - pip==18.0
  - wheel==0.31.1
  - sphinx==1.7.5
  - sphinx_rtd_theme==0.4.1
  - dask==0.13.0
  - numpy==1.11.3
  - pims==0.3.3
  - slicerator==0.9.8
  - pip:
    - slicerator==0.9.8
