name: dask_image_doc_env

channels:
  - conda-forge

dependencies:
  - pip==20.2.4
  - wheel==0.35.1
  - sphinx==3.2.1
  - jinja2<3.1
  - dask==2.8.1
  - numpy==1.15.4
  - pims==0.4.1
  - slicerator==0.9.8
  - pip:
      - slicerator==0.9.8
      - dask-sphinx-theme>=2
