name: dask_image_py27_env

channels:
  - defaults
  - conda-forge

dependencies:
  - python=2.7.*
  - pip==18.0
  - wheel==0.31.1
  - coverage==4.5.1
  - flake8==3.7.2
  - numpy==1.11.3
  - scipy==1.1.0
  - pims==0.4.1
  - slicerator==0.9.8
  - pip:
    - slicerator==0.9.8
    - pytest==3.8.2
    - pytest-flake8==1.0.4
    - dask==0.16.1
    - scikit-image==0.14.2
