name: dask_image_py35_env

channels:
  - conda-forge

dependencies:
  - python=3.5.*
  - pip==18.0
  - wheel==0.31.1
  - coverage==4.5.1
  - pytest==3.0.5
  - dask==0.13.0
  - numpy==1.11.3
  - scipy==1.0.0
  - scikit-image=0.12.3
  - pims==0.4.1
  - slicerator==0.9.8
  - pip:
    - slicerator==0.9.8
