name: dask-image-testenv

channels:
  - conda-forge

dependencies:
  - python=3.8.*
  - pip==22.0.3
  - wheel==0.37.1
  - coverage==6.3.1
  - flake8==4.0.1
  - pytest==7.0.0
  - pytest-flake8==1.0.7
  - dask==2.8.1
  - numpy==1.22.2
  - scipy==1.8.0
  - scikit-image==0.19.1
  - pims==0.5
  - slicerator==1.0.0
