name: dask-image-testenv

channels:
  - conda-forge

dependencies:
  - python=3.6.*
  - pip==19.0.1
  - wheel==0.32.3
  - coverage==4.5.2
  - flake8==3.7.2
  - pytest==5.2.0
  - pytest-flake8==1.0.4
  - dask==2.8.1
  - numpy==1.15.4
  - scipy==1.2.0
  - scikit-image==0.14.2
  - pims==0.4.1
  - slicerator==0.9.8
