name: dask-image-testenv

channels:
  - conda-forge

dependencies:
  - python=3.12.*
  - pip==24.0
  - coverage==7.5.1
  - flake8==7.0.0
  - pytest==8.2.0
  - pytest-cov==5.0.0
  - pytest-flake8==1.1.1
  - pytest-timeout >=2.3.1
  - dask==2024.4.1
  - numpy==1.26.4
  - scipy==1.13.0
  - scikit-image==0.22.0
  - pims==0.6.1
  - slicerator==1.1.0
  - pandas==2.2.2
  - pip:
    - build==1.2.1