name: dask-image-testenv

channels:
  - conda-forge

dependencies:
  - python=3.8.*
  - pip>=19.3.1
  - wheel>=0.33.6
  - coverage>=4.5.4
  - flake8>=3.7.9
  - pytest>=5.3.1
  - pytest-flake8>=1.0.4
  - dask==2.8.1
  - numpy>=1.17.3
  - scipy>=1.3.2
  - scikit-image>=0.16.2
  - pims>=0.4.1
  - slicerator
