name: dask-image-testenv

channels:
  - conda-forge

dependencies:
  - python=3.10.*
  - pip==23.0.1
  - coverage==7.2.1
  - flake8==6.0.0
  - pytest==7.2.2
  - pytest-cov==4.0.0
  - pytest-flake8==1.1.1
  - dask==2024.4.1
  - numpy==1.24.2
  - scipy==1.10.1
  - scikit-image==0.19.3
  - pims==0.6.1
  - slicerator==1.1.0
  - pandas==2.0.0
  - pip:
    - build==1.2.1